name: CI

on:
  push:
    branches-ignore: [ "main" ]
  workflow_dispatch:
permissions:
  contents: read
  pull-requests: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: sudo apt-get update && sudo apt-get install -y build-essential libglew-dev libglfw3-dev
      - name: Build du projet
        run: |
          mkdir build
          cd build
          cmake ..
          make
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: sudo apt-get update && sudo apt-get install -y libboost-all-dev
      - name: Execution des tests
        run: | 
          mkdir build 
          cd build 
          cmake ../tests
          make 
          cd tests
          ./ZephyrTests
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: sudo apt-get update && sudo apt-get install -y clang
      - name: Check format code
        run: |
          find . -name '*.cpp' -o -name '*.h' | xargs clang-format --dry-run --Werror
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: sudo apt-get update && sudo apt-get install -y cppcheck
      - name: Analyse
        run: |
          cppcheck --enable=all --inconclusive --std=c++20 --force --suppress=missingIncludeSystem --quiet src
