name: CI

on:
  push:
    branches-ignore: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Vérification des leaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          sudo apt-get update && sudo apt-get install -y git curl
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo bash -
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y nodejs
      - name: Vérification des versions
        run: |
          git --version
          node --version
          npm --version
          npx commitlint --version
      - name: Installation de commitlint
        run: |
          npm install --save-dev commitlint@latest @commitlint/config-conventional
      - name: Valider le commit
        if: github.event_name == 'push'
        run: npx commitlint --last --verbose
      - name: Valider le PR
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: sudo apt-get update && sudo apt-get install -y build-essential libglew-dev libglfw3-dev
      - name: Build du projet
        run: mkdir build && cd build && cmake ../cmake && make
